### ISSUE TITLE
Fix border colors

### ISSUE THREAD

**Issue by raphael-arce** [GroceryFlux/GroceriesApp#25]
* only make it colored when empty, 
* search bar in item list without colored border
* add warning when creating a list without title

**Comment by samiletuns** [comment]
removed the outline when focused

**Comment by samiletuns** [comment]
Added warning to confirm that list is saved without title (then saves title as "No title"), otherwise confirm to delete

**Comment by samiletuns** [comment]
* remove red border from add items, only add red border when + is clicked and item name is empty
* remove warning when coming back to home menu, do not save list when there is no title and no items (save list when either or both title or items are present)
